# Generated by Django 4.2.20 on 2025-05-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('CONF', 'Конференция'), ('SEM', 'Семинар'), ('WORK', 'Мастер-класс'), ('EXH', 'Выставка'), ('CONC', 'Концерт'), ('OTH', 'Другое')], default='OTH', max_length=4, verbose_name='Тип мероприятия')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок регистрации')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('online_event', models.BooleanField(default=False, verbose_name='Онлайн-мероприятие')),
                ('online_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для онлайн-участия')),
                ('organizer', models.CharField(max_length=255, verbose_name='Организатор')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано'), (True, 'Отменено'), (True, 'Завершено')], default=1, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime'], name='events_even_start_d_b72861_idx'), models.Index(fields=['is_published'], name='events_even_is_publ_cc4b67_idx'), models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx')],
            },
        ),
    ]
