# Generated by Django 4.2.20 on 2025-06-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CONF', 'Конференция'), ('SEM', 'Семинар'), ('WORK', 'Мастер-класс'), ('EXH', 'Выставка'), ('CONC', 'Концерт'), ('VOL', 'Волонтёрская акция'), ('CHAR', 'Благотворительное мероприятие'), ('ECO', 'Экологическая акция'), ('CAREER', 'Карьерное консультирование'), ('SOC', 'Социальное взаимодействие'), ('CULT', 'Культурное мероприятие'), ('OTH', 'Другое')], default='OTH', max_length=8, verbose_name='Тип мероприятия'),
        ),
    ]
