# Generated by Django 4.2.20 on 2025-04-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titel',
            new_name='title',
        ),
    ]
