# Generated by Django 4.2.20 on 2025-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
    ]
