# Generated by Django 4.2.20 on 2025-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_uploadfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_photos/%Y/', verbose_name='Фото'),
        ),
    ]
